### ISSUE TITLE
Firefox extension - don't require manual refresh

### ISSUE THREAD

**Issue by eric-kimbrel** [Sotera/Datawake-Legacy#34]
Currently the firefox extension requires a user to manualy refresh a new tab page to access the datawake new tab page.   This needs to be easier.  We could either:
1. Fix so a refresh is not required
2. Replace the new tab page and put that functionality in the panel itself instead (won't match the chrome extension)

**Comment by ghost** [comment]
Changed the listener to use open instead of ready.
